# Dataframe
Un _dataframe_ è una collezione di serie che hanno lo stesso indice, ed è
quindi un insieme di osservazioni di vari _caratteri_ per una popolazione di
individui. Tra i vari modi che sono disponibili in pandas per creare un
_dataframe_, noi faremo riferimento al metodo `read_csv` della classe
`pd.DataFrame`, che permette di leggere i contenuti di un file in formato CSV e
convertirli automaticamente in un _dataframe_.

In [1]:
import pandas as pd

heroes = pd.read_csv('data/heroes.csv', sep=';', index_col=0)

Usando lo stesso file a cui abbiamo fatto riferimento nei paragrafi precedenti,
è stato necessario utilizzare l'argomento opzionale `sep` per indicare il
carattere usato per separare i campi in ogni record. La visualizzazione dei
dataframe viene automaticamente formattata in un formato tabellare facile da
leggere se si utilizza jupyter:

In [2]:
heroes

,Identity,Birth place,Publisher,Height,Weight,Gender,First appearance,Eye color,Hair color,Strength,Intelligence
Name,,,,,,,,,,,
A-Bomb,Richard Milhouse Jones,"Scarsdale, Arizona",Marvel Comics,203.21,441.95,M,2008.0,Yellow,No Hair,100.0,moderate
Abraxas,Abraxas,Within Eternity,Marvel Comics,NaN,NaN,M,NaN,Blue,Black,100.0,high
Abomination,Emil Blonsky,"Zagreb, Yugoslavia",Marvel Comics,203.04,441.98,M,NaN,Green,No Hair,80.0,good
Adam Monroe,NaN,NaN,NBC - Heroes,NaN,NaN,M,NaN,Blue,Blond,10.0,good
Agent 13,Sharon Carter,NaN,Marvel Comics,173.41,61.03,F,NaN,Blue,Blond,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
Alan Scott,Alan Ladd Wellington Scott,Gotham City,DC Comics,180.98,90.81,M,1940.0,Blue,Blond,80.0,good
Amazo,NaN,NaN,DC Comics,257.49,173.95,M,1960.0,Red,NaN,100.0,good
Ant-Man,Hank Pym,"Elmsford, New York",Marvel Comics,211.74,122.44,M,1962.0,Blue,Blond,20.0,high
Ajax,Francis,NaN,Marvel Comics,193.34,90.63,M,1998.0,Brown,Black,50.0,average
Alex Mercer,Alexander J. Mercer,NaN,Wildstorm,NaN,NaN,M,NaN,NaN,NaN,80.0,average

Ci riferiremo spesso alle righe e alle colonne di un _dataframe_ per indicare
rispettivamente le osservazioni e i caratteri. Per esempio la prima riga si
riferisce all'osservazione relativa ad "A-Bomb", mentre la prima colonna
corrisponde al carattere "identity". Vi sono molti modi per interagire con un
_dataframe_:

- l'insieme degli indici, dei caratteri e dei valori si ottengono, nell'ordine,
  alle proprietà `index`, `columns` e `values`;
- una serie corrispondente a una colonna/carattere può essere selezionata
  usando una sintassi simile a quella dei dizionari, specificando il nome del
  carattere come chiave:

In [3]:
heroes['Gender']

Name
A-Bomb         M
Abraxas        M
Abomination    M
Adam Monroe    M
Agent 13       F
              ..
Alan Scott     M
Amazo          M
Ant-Man        M
Ajax           M
Alex Mercer    M
Name: Gender, Length: 735, dtype: object

```{admonition} Nomenclatura
:class: naming
In alternativa è possibile usare una sintassi basata su _dot notation_ in cui
il nome della colonna, senza essere racchiuso tra apici, segue il _dataframe_.
In altre parole, `heroes['Gender']` e `heroes.Gender` sono equivalenti. Questa
seconda notazione è però utilizzabile solamente se non vi sono spazi nei nomi
delle colonne. Nel seguito utilizzeremo quindi sempre la prima delle due
notazioni.
```

- tramite uno _slicing_ sulle posizioni o sui valori dell'indice è possibile
  selezionare un sottoinsieme delle righe del _dataframe_ (e come nel caso
  delle serie, l'estremo superiore è incluse se si usano gli indici ed escluso
  se si usano le posizioni):

In [4]:
heroes['Agent 13':'Air-Walker']

,Identity,Birth place,Publisher,Height,Weight,Gender,First appearance,Eye color,Hair color,Strength,Intelligence
Name,,,,,,,,,,,
Agent 13,Sharon Carter,NaN,Marvel Comics,173.41,61.03,F,NaN,Blue,Blond,NaN,NaN
Air-Walker,Gabriel Lan,"Xandar, a planet in the Tranta system, Androme...",Marvel Comics,188.59,108.23,M,NaN,Blue,White,85.0,average

Queste modalità di accesso possono effettivamente creare confusione: usando una
sintassi molto simile, specificando un valore si accede a una colonna e
specificando uno _slice_ si accede a un insieme di righe. Per scrivere codice
più chiaro è meglio selezionare le righe utilizzando le proprietà `loc` e
`iloc` nello stesso modo in cui queste funzionano per le serie, con la
differenza che quando queste sono usate specificando un solo valore, viene
restituita una serie, e quando sono utilizzate con uno _slice_ o con una lista
viene restituito un _dataframe_.

In [5]:
heroes.loc['Professor X']

Identity            Charles Francis Xavier
Birth place             New York, New York
Publisher                    Marvel Comics
Height                              183.74
Weight                               86.89
Gender                                   M
First appearance                    1963.0
Eye color                             Blue
Hair color                         No Hair
Strength                              10.0
Intelligence                          high
Name: Professor X, dtype: object

In [6]:
heroes.iloc[42:46]

,Identity,Birth place,Publisher,Height,Weight,Gender,First appearance,Eye color,Hair color,Strength,Intelligence
Name,,,,,,,,,,,
Warbird,Carol Danvers,"Boston, Massachusetts",Marvel Comics,180.56,54.75,F,NaN,Blue,Blond,NaN,NaN
Wildfire,Drake Burroughs,NaN,DC Comics,NaN,NaN,M,NaN,NaN,NaN,35.0,average
Vulture,Adrian Toomes,"Staten Island, New York City",Marvel Comics,180.61,79.63,M,NaN,Brown,No Hair,25.0,good
Warp,Emil LaSalle,NaN,DC Comics,173.42,67.42,M,1981.0,Brown,Black,10.0,moderate

È inoltre possibile selezionare una o più righe e visualizzare solo un
sottoinsieme dei caratteri, passando a `loc` o `iloc` un secondo argomento in
cui si specificano i caratteri da mostrare, utilizzando anche in questo caso un
valore, una lista di valori oppure uno _slice_:

In [7]:
heroes.loc['Professor X', 'Height':'Weight']

Height    183.74
Weight     86.89
Name: Professor X, dtype: object

Va notato che `loc` accetta solo valori simbolici, mentre `iloc` solamente
posizioni, e ciò riguarda anche il loro secondo argomento:

In [8]:
heroes.iloc[[106, 103], [3, 4]]

           Height  Weight
Name
Tempest    163.02   54.36
Supergirl  165.40   54.80

Volendo accedere direttamente a un elemento è possibile utilizzare le proprietà `at` e `iat`:

In [9]:
heroes.at['Superman', 'Strength']

100.0

In [10]:
heroes.iat[500, -1]

'high'

```{admonition} Nomenclatura
:class: naming
È anche possibile utilizzare `loc` e `iloc` per estrarre un singolo elemento:
per esempio, `heroes.loc['Superman', 'Strength']` equivale alla prima delle due
istruzioni appena elencate. Tuttavia, `at` e `iat` sono implementate in modo da
essere più efficienti.
```

È infine possibile riordinare le righe di un dataframe invocando i metodi
`sort_values` e `sort_index`: il primo basa l'ordinamento sul valore di una
colonna, il cui nome va specificato tramite l'argomento `by` e il secondo è
invece basato sui valori dell'indice. È inoltre possibile indicare un valore
booleano per l'argomento `ascending` che permette di ordinare in verso
crescente o decrescente.

In [11]:
heroes.sort_values(by='Weight', ascending=False)[:5]

,Identity,Birth place,Publisher,Height,Weight,Gender,First appearance,Eye color,Hair color,Strength,Intelligence
Name,,,,,,,,,,,
Sasquatch,Walter Langkowski,"Edmonton, Alberta, Canada",Marvel Comics,305.02,900.70,M,NaN,Red,Orange,80.0,good
Juggernaut,Cain Marko,"Berkeley, California",Marvel Comics,287.95,855.82,M,1965.0,Blue,Red,100.0,average
Darkseid,Uxas,NaN,DC Comics,267.37,817.57,M,1970.0,Red,No Hair,100.0,high
Hulk,Bruce Banner,"Dayton, Ohio",Marvel Comics,244.40,630.90,M,1962.0,Green,Green,100.0,high
Giganta,Doris Zuel,NaN,DC Comics,62.65,630.80,F,1944.0,Green,Red,90.0,high

In [12]:
heroes.sort_index()[-5:]

,Identity,Birth place,Publisher,Height,Weight,Gender,First appearance,Eye color,Hair color,Strength,Intelligence
Name,,,,,,,,,,,
Yellowjacket II,Rita DeMara,NaN,Marvel Comics,165.58,52.36,F,NaN,Blue,Strawberry Blond,10.0,average
Ymir,Ymir,Niffleheim,Marvel Comics,304.63,NaN,M,NaN,White,No Hair,100.0,average
Yoda,Yoda,NaN,George Lucas,66.29,17.01,M,1980.0,Brown,White,55.0,high
Zatanna,Zatanna Zatara,NaN,DC Comics,170.29,57.77,F,NaN,Blue,Black,10.0,high
Zoom,Hunter Zolomon,NaN,DC Comics,185.90,81.93,M,NaN,Red,Brown,10.0,average

Va notato che entrambi i metodi restituiscono una copia del _dataframe_. Anche
per i _dataframe_ è possibile utilizzare una lista di valori booleani che
identificano le righe da selezionare, e tale lista può essere prodotta
effettuando una query. In questo caso però le condizioni possono riguardare le
varie colonne, ognuna delle quali va specificata usando una delle due sintassi
precedentemente introdotte (quella analoga ai dizionari oppure quella basata
su _dot notation_). Per esempio possiamo selezionare gli eroi per cui l'anno
di apparizione esiste e rappresenta un valore non fuori scala nel modoseguente:

In [13]:
heroes_with_year = heroes[heroes['First appearance'] > 1900]
heroes_with_year.head()

,Identity,Birth place,Publisher,Height,Weight,Gender,First appearance,Eye color,Hair color,Strength,Intelligence
Name,,,,,,,,,,,
A-Bomb,Richard Milhouse Jones,"Scarsdale, Arizona",Marvel Comics,203.21,441.95,M,2008.0,Yellow,No Hair,100.0,moderate
Agent Bob,Bob,NaN,Marvel Comics,178.25,81.45,M,2007.0,Brown,Brown,10.0,low
Abe Sapien,Abraham Sapien,NaN,Dark Horse Comics,191.24,65.35,M,1993.0,Blue,No Hair,30.0,high
Abin Sur,NaN,Ungara,DC Comics,185.52,90.90,M,1959.0,Blue,No Hair,90.0,average
Animal Man,Bernhard Baker,NaN,DC Comics,183.80,83.39,M,1965.0,Blue,Blond,50.0,average